{
 "title": "Gitlab_pipeline_dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group_id",
    "query": {
     "query": "label_values(gitlab_pipeline_duration_seconds,group_id)"
    }
   },
   {
    "name": "path_with_namespace",
    "query": {
     "query": "label_values(gitlab_pipeline_duration_seconds{group_id=~\"$group_id\"},path_with_namespace)"
    }
   },
   {
    "name": "source",
    "query": {
     "query": "label_values(gitlab_pipeline_duration_seconds{group_id=~\"$group_id\", path_with_namespace=~\"$path_with_namespace\"},source)"
    }
   },
   {
    "name": "ref",
    "query": {
     "query": "label_values(gitlab_pipeline_duration_seconds{group_id=~\"$group_id\", path_with_namespace=~\"$path_with_namespace\", source=~\"$source\"},ref)"
    }
   },
   {
    "name": "status",
    "query": {
     "query": "label_values(gitlab_pipeline_duration_seconds{group_id=~\"$group_id\", path_with_namespace=~\"$path_with_namespace\", source=~\"$source\", ref=~\"$ref\"},status)"
    }
   },
   {
    "name": "pipeline_id",
    "query": {
     "query": "label_values(gitlab_pipeline_duration_seconds{group_id=~\"$group_id\", path_with_namespace=~\"$path_with_namespace\", source=~\"$source\", ref=~\"$ref\", status=~\"$status\"},pipeline_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pipeline_executed_status_pie_chart - [Group: $group_id] [Project: $path_with_namespace] [Source: $source] [Ref: $ref] [Pipeline: $pipeline_id] [Status: $status]",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(gitlab_pipeline_duration_seconds{\n    group_id=~\"$group_id\",\n    path_with_namespace=~\"$path_with_namespace\",\n    source=~\"$source\",\n    ref=~\"$ref\",\n    pipeline_id=~\"$pipeline_id\",\n    status=~\"$status\"\n}[$__range:$__interval]))\nby (status)"
    }
   ]
  },
  {
   "title": "Pipeline_executed_counts_for_every_$__interval - [Group: $group_id] [Project: $path_with_namespace] [Source: $source] [Ref: $ref] [Pipeline: $pipeline_id] [Status: $status]",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(count_over_time(gitlab_pipeline_duration_seconds{\n    group_id=~\"$group_id\",\n    path_with_namespace=~\"$path_with_namespace\",\n    source=~\"$source\",\n    ref=~\"$ref\",\n    pipeline_id=~\"$pipeline_id\",\n    status=~\"$status\"\n}[$__interval]))",
     "legendFormat": "hourly_executed_counts"
    }
   ]
  },
  {
   "title": "Pipeline_duration_in_time_series - [Group: $group_id] [Project: $path_with_namespace] [Source: $source] [Ref: $ref] [Pipeline: $pipeline_id] [Status: $status]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gitlab_pipeline_duration_seconds{\n    group_id=~\"$group_id\",\n    path_with_namespace=~\"$path_with_namespace\",\n    source=~\"$source\",\n    ref=~\"$ref\",\n    pipeline_id=~\"$pipeline_id\",\n    status=~\"$status\"\n}",
     "legendFormat": "[{{status}}] [{{pipeline_id}}] [{{ref}}] [{{source}}] [{{path_with_namespace}}] [{{group_id}}]"
    }
   ]
  },
  {
   "title": "[Group: $group_id] [Project: $path_with_namespace] [Source: $source] [Ref: $ref] [Pipeline: $pipeline_id] [Status: $status] - Pipeline_overview_table",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "gitlab_pipeline_duration_seconds{\n    group_id=~\"$group_id\",\n    path_with_namespace=~\"$path_with_namespace\",\n    source=~\"$source\",\n    ref=~\"$ref\",\n    pipeline_id=~\"$pipeline_id\",\n    status=~\"$status\"\n}"
    },
    {
     "expr": "gitlab_pipeline_queued_duration_seconds{\n    group_id=~\"$group_id\",\n    path_with_namespace=~\"$path_with_namespace\",\n    source=~\"$source\",\n    ref=~\"$ref\",\n    pipeline_id=~\"$pipeline_id\",\n    status=~\"$status\"\n}"
    }
   ]
  },
  {
   "title": "Pipeline_duration_for_given_time_range - [Group: $group_id] [Project: $path_with_namespace] [Source: $source] [Ref: $ref]",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "repeat": "source",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum_over_time(gitlab_pipeline_duration_seconds{\n    group_id=~\"$group_id\",\n    path_with_namespace=~\"$path_with_namespace\",\n    source=~\"$source\",\n    ref=~\"$ref\",\n    status=~\"$status\"\n}[$__range:$__interval]))\nby (group_id,path_with_namespace,source)",
     "legendFormat": "max_duration - [{{path_with_namespace}}]"
    },
    {
     "expr": "avg(sum_over_time(gitlab_pipeline_duration_seconds{\n    group_id=~\"$group_id\",\n    path_with_namespace=~\"$path_with_namespace\",\n    source=~\"$source\",\n    ref=~\"$ref\",\n    status=~\"$status\"\n}[$__range:$__interval]))\nby (group_id,path_with_namespace,source)",
     "legendFormat": "avg_duration - [{{path_with_namespace}}]"
    }
   ]
  },
  {
   "title": "Pipeline_queued_duration_for_given_time_range - [Group: $group_id] [Project: $path_with_namespace] [Source: $source] [Ref: $ref]",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "repeat": "source",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum_over_time(gitlab_pipeline_queued_duration_seconds{\n    group_id=~\"$group_id\",\n    path_with_namespace=~\"$path_with_namespace\",\n    source=~\"$source\",\n    ref=~\"$ref\",\n    status=~\"$status\"\n}[$__range:$__interval]))\nby (group_id,path_with_namespace,source)",
     "legendFormat": "max_queued_duration - [{{path_with_namespace}}]"
    },
    {
     "expr": "avg(sum_over_time(gitlab_pipeline_queued_duration_seconds{\n    group_id=~\"$group_id\",\n    path_with_namespace=~\"$path_with_namespace\",\n    source=~\"$source\",\n    ref=~\"$ref\",\n    status=~\"$status\"\n}[$__range:$__interval]))\nby (group_id,path_with_namespace,source)",
     "legendFormat": "avg_queued_duration - [{{path_with_namespace}}]"
    }
   ]
  }
 ]
}