{
 "title": "Gitlab_job_dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "pipeline_id",
    "query": {
     "query": "label_values(gitlab_job_duration_seconds,pipeline_id)"
    }
   },
   {
    "name": "job_name",
    "query": {
     "query": "label_values(gitlab_job_duration_seconds{pipeline_id=~\"$pipeline_id\"},job_name)"
    }
   },
   {
    "name": "status",
    "label": "status",
    "query": {
     "query": "label_values(gitlab_job_duration_seconds{pipeline_id=~\"$pipeline_id\"},status)"
    }
   },
   {
    "name": "source",
    "query": {
     "query": "label_values(gitlab_job_duration_seconds{status=~\"$status\", pipeline_id=~\"$pipeline_id\"},source)"
    }
   },
   {
    "name": "path_with_namespace",
    "query": {
     "query": "label_values(gitlab_job_duration_seconds{status=~\"$status\", pipeline_id=~\"$pipeline_id\"},path_with_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Job_executed_status_pie_chart - [Job: $job_name] [Status: $status] [Pipeline: $pipeline_id]",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(gitlab_job_duration_seconds{\n    pipeline_id=~\"$pipeline_id\",\n    job_name=~\"$job_name\",\n    status=~\"$status\"\n}[$__range:$__interval]))\nby (status)"
    }
   ]
  },
  {
   "title": "Job_executed_counts_for_every_$__interval - [Job: $job_name] [Status: $status] [Pipeline: $pipeline_id]",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time(gitlab_job_duration_seconds{\n    pipeline_id=~\"$pipeline_id\",\n    job_name=~\"$job_name\",\n    status=~\"$status\"\n}[$__interval]))"
    }
   ]
  },
  {
   "title": "Job_duration_in_time_series - [Job: $job_name] [Status: $status] [Pipeline: $pipeline_id]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "gitlab_job_duration_seconds{\n    pipeline_id=~\"$pipeline_id\",\n    job_name=~\"$job_name\",\n    status=~\"$status\"\n}",
     "legendFormat": "[{{status}}] [{{job_name}}] [{{pipeline_id}}]"
    }
   ]
  },
  {
   "title": "Job_queued_duration_in_time_series - [Job: $job_name] [Status: $status] [Pipeline: $pipeline_id]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "gitlab_job_queued_duration_seconds{\n    pipeline_id=~\"$pipeline_id\",\n    job_name=~\"$job_name\",\n    status=~\"$status\"\n}",
     "legendFormat": "[{{status}}] [{{job_name}}] [{{pipeline_id}}]"
    }
   ]
  },
  {
   "title": "Job_overview_table - [Job: $job_name] [Status: $status] [Pipeline: $pipeline_id]",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "gitlab_job_duration_seconds{\n    pipeline_id=~\"$pipeline_id\",\n    job_name=~\"$job_name\",\n    status=~\"$status\"\n}"
    },
    {
     "expr": "gitlab_job_queued_duration_seconds{\n    pipeline_id=~\"$pipeline_id\",\n    job_name=~\"$job_name\",\n    status=~\"$status\"\n}"
    }
   ]
  },
  {
   "title": "job_duration_for_given_time_range - [Job: $job_name] [Source: $source] [Project: $path_with_namespace]",
   "type": "bargauge",
   "description": "This chart is used to display the average job duration of specific jobs within [Pipeline: $pipeline_id] during the given time range.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum_over_time(gitlab_job_duration_seconds{\n    path_with_namespace=~\"$path_with_namespace\",\n    source=~\"$source\",\n    job_name=~\"$job_name\",\n    status=~\"$status\"\n}[$__range:$__interval]))\nby (path_with_namespace, source, job_name)",
     "legendFormat": "avg_job_duration: [{{job_name}}]"
    },
    {
     "expr": "max(sum_over_time(gitlab_job_duration_seconds{\n    path_with_namespace=~\"$path_with_namespace\",\n    source=~\"$source\",\n    job_name=~\"$job_name\",\n    status=~\"$status\"\n}[$__range:$__interval]))\nby (path_with_namespace, source, job_name)",
     "legendFormat": "max_job_duration: [{{job_name}}]"
    }
   ]
  },
  {
   "title": "job_queued_duration_for_given_time_range - [Job: $job_name] [Source: $source] [Project: $path_with_namespace]",
   "type": "bargauge",
   "description": "This chart is used to display the average job duration of specific jobs within [Pipeline: $pipeline_id] during the given time range.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum_over_time(gitlab_job_queued_duration_seconds{\n    path_with_namespace=~\"$path_with_namespace\",\n    source=~\"$source\",\n    job_name=~\"$job_name\",\n    status=~\"$status\"\n}[$__range:$__interval]))\nby (path_with_namespace, source, job_name)",
     "legendFormat": "avg_job_queued_duration(s)"
    },
    {
     "expr": "max(sum_over_time(gitlab_job_queued_duration_seconds{\n    path_with_namespace=~\"$path_with_namespace\",\n    source=~\"$source\",\n    job_name=~\"$job_name\",\n    status=~\"$status\"\n}[$__range:$__interval]))\nby (path_with_namespace, source, job_name)",
     "legendFormat": "max_job_queued_duration(s)"
    }
   ]
  }
 ]
}