{
 "title": "Gitlab_Runner_dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "runner_description",
    "query": {
     "query": "label_values(gitlab_job_duration_seconds,runner_description)"
    }
   },
   {
    "name": "job_name",
    "query": {
     "query": "label_values(gitlab_job_duration_seconds{runner_description=~\"$runner_description\"},job_name)"
    }
   },
   {
    "name": "job_id",
    "query": {
     "query": "label_values(gitlab_job_duration_seconds{runner_description=~\"$runner_description\", job_name=~\"$job_name\"},job_id)"
    }
   },
   {
    "name": "status",
    "label": "status",
    "query": {
     "query": "label_values(gitlab_job_duration_seconds{runner_description=~\"$runner_description\"},status)"
    }
   },
   {
    "name": "path_with_namespace",
    "query": {
     "query": "label_values(gitlab_job_duration_seconds{pipeline_id=~\"$pipeline_id\"},path_with_namespace)"
    }
   },
   {
    "name": "source",
    "query": {
     "query": "label_values(gitlab_job_duration_seconds{pipeline_id=~\"$pipeline_id\"},source)"
    }
   },
   {
    "name": "pipeline_id",
    "query": {
     "query": "label_values(gitlab_pipeline_duration_seconds,pipeline_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Runner_job_executed_status_pie_chart - [Runner: $runner_description] [job: $job_name]",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "repeat": "runner_description",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(gitlab_job_duration_seconds{\n    runner_description=~\"$runner_description\",\n    job_name=~\"$job_name\",\n    status=~\"$status\"\n}[$__range:$__interval]))\nby (status)"
    }
   ]
  },
  {
   "title": "Runner_job_overview_table - [Runner: $runner_description] [job: $job_name]",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "repeat": "runner_description",
   "targets": [
    {
     "expr": "gitlab_job_duration_seconds{\n    runner_description=~\"$runner_description\",\n    job_name=~\"$job_name\",\n    status=~\"$status\"\n}"
    },
    {
     "expr": "gitlab_job_queued_duration_seconds{\n    runner_description=~\"$runner_description\",\n    job_name=~\"$job_name\",\n    status=~\"$status\"\n}"
    }
   ]
  },
  {
   "title": "Runner_job_executed_counts_every_$__interval - [Runner: $runner_description] [job: $job_name] ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "repeat": "runner_description",
   "targets": [
    {
     "expr": "sum(count_over_time(gitlab_job_duration_seconds{\n    runner_description=~\"$runner_description\",\n    job_name=~\"$job_name\",\n    status=~\"$status\"\n}[$__interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Runner_job_duration_in_time_series - [Runner: $runner_description] [job: $job_name]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "repeat": "runner_description",
   "targets": [
    {
     "expr": "gitlab_job_duration_seconds{\n    runner_description=~\"$runner_description\",\n    job_name=~\"$job_name\",\n    status=~\"$status\"\n}",
     "legendFormat": "[runner: {{runner_description}}] [job_name: {{job_name}}] [job_id: {{job_id}}] [status: {{status}}]"
    }
   ]
  },
  {
   "title": "Runner_job_max_duration_for_every_$__interval - [Runner: $runner_description] [job: $job_name]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "max(max_over_time(gitlab_job_duration_seconds{\n    runner_description=~\"$runner_description\",\n    job_name=~\"$job_name\",\n    status=~\"$status\"\n}[$__interval])) by (runner_description)",
     "legendFormat": "[{{runner_description}}]"
    }
   ]
  },
  {
   "title": "Runner_job_average_duration_for_every_$__interval - [Runner: $runner_description] [job: $job_name]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "avg(sum_over_time(gitlab_job_duration_seconds{\n    runner_description=~\"$runner_description\",\n    job_name=~\"$job_name\",\n    status=~\"$status\"\n}[$__interval])) by (runner_description)",
     "legendFormat": "[{{runner_description}}]"
    }
   ]
  },
  {
   "title": "Runner_job_sum_duration_for_every_$__interval - [Runner: $runner_description] [job: $job_name]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(sum_over_time(gitlab_job_duration_seconds{\n    runner_description=~\"$runner_description\",\n    job_name=~\"$job_name\",\n    status=~\"$status\"\n}[$__interval])) by (runner_description)",
     "legendFormat": "[{{runner_description}}]"
    }
   ]
  },
  {
   "title": "Runner_job_queued_duration_in_time_series - [Runner: $runner_description] [job: $job_name]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "repeat": "runner_description",
   "targets": [
    {
     "expr": "gitlab_job_queued_duration_seconds{\n    runner_description=~\"$runner_description\",\n    job_name=~\"$job_name\",\n    status=~\"$status\"\n}",
     "legendFormat": "[runner: {{runner_description}}] [job_name: {{job_name}}] [job_id: {{job_id}}] [status: {{status}}]"
    }
   ]
  },
  {
   "title": "Runner_job_max_queued_duration_for_every_$__interval - [Runner: $runner_description] [job: $job_name]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "max(max_over_time(gitlab_job_queued_duration_seconds{\n    runner_description=~\"$runner_description\",\n    job_name=~\"$job_name\",\n    status=~\"$status\"\n}[$__interval])) by (runner_description)",
     "legendFormat": "[{{runner_description}}]"
    }
   ]
  },
  {
   "title": "Runner_job_average_queued_duration_for_every_$__interval - [Runner: $runner_description] [job: $job_name]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "avg(sum_over_time(gitlab_job_queued_duration_seconds{\n    runner_description=~\"$runner_description\",\n    job_name=~\"$job_name\",\n    status=~\"$status\"\n}[$__interval])) by (runner_description)",
     "legendFormat": "[{{runner_description}}]"
    }
   ]
  },
  {
   "title": "Runner_job_sum_queued_duration_for_every_$__interval - [Runner: $runner_description] [job: $job_name]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum(sum_over_time(gitlab_job_queued_duration_seconds{\n    runner_description=~\"$runner_description\",\n    job_name=~\"$job_name\",\n    status=~\"$status\"\n}[$__interval])) by (runner_description)",
     "legendFormat": "[{{runner_description}}]"
    }
   ]
  }
 ]
}